#!/usr/bin/env bash
# lite Block Design VCS simulation: HBM + real axi_cdma + force xdma_0/M_AXI.
set -euo pipefail

BD_SIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LITE_BD_DIR="$(cd "$BD_SIM_DIR/.." && pwd)"
REPO_ROOT="$(cd "$LITE_BD_DIR/../../.." && pwd)"
# shellcheck source=../../../vpu/tb/sim/vcs_common.sh
source "$REPO_ROOT/rtl/vpu/tb/sim/vcs_common.sh"

vcs_setup

BUILD_DIR="$BD_SIM_DIR/build_bd_sim"
DATA_DIR="$LITE_BD_DIR/data"
GOLDEN_PY="$DATA_DIR/golden_conv_inst.py"
TB_TOP="tb_lite_bd_e2e"
EXPORT_VCS_DIR="$REPO_ROOT/sim/lite_bd_export/vcs/lite/vcs"
BD_SCALE="${BD_SCALE:-${E2E_SCALE:-0.1}}"
BD_CASE="${BD_CASE:-${E2E_CASE:-default}}"
BD_VERIFY_WORDS="${BD_VERIFY_WORDS:-${E2E_VERIFY_WORDS:-0}}"
BD_MODE="${BD_MODE:-fast}"  # fast=on-chip preload, hbm=HBM-first (most hardware-faithful)
RUN_EXPORT="${RUN_EXPORT:-0}"
SKIP_LITE_COMPILE="${SKIP_LITE_COMPILE:-1}"
VCS_DUMP="${VCS_DUMP:-0}"
DUMP_FSDB="${DUMP_FSDB:-$BUILD_DIR/tb_lite_bd_e2e.fsdb}"

if [[ "$RUN_EXPORT" == "1" ]]; then
  echo "=== Vivado export_simulation (lite BD) ==="
  vivado -mode batch -source "$REPO_ROOT/scripts/chip-lite/4_export_sim.tcl" \
    2>&1 | tee "$REPO_ROOT/sim/lite_bd_export/export.log"
fi

case "$BD_MODE" in
  fast|onchip|bd-fast)
    GOLDEN_BD_ARG="--bd-sim-fast"
    SIM_PLUSARGS="+FAST_ONCHIP_LOAD +INST_READMEMH"
    ;;
  hbm|hbm-first|bd-hbm)
    GOLDEN_BD_ARG="--bd-sim"
    SIM_PLUSARGS="+INST_READMEMH"
    ;;
  *)
    echo "ERROR: unknown BD_MODE=$BD_MODE (use fast or hbm)" >&2
    exit 1
    ;;
esac

echo "=== Generate golden (BD mode=$BD_MODE) case=$BD_CASE ==="
python3 "$GOLDEN_PY" --case "$BD_CASE" --scale "$BD_SCALE" \
  --verify-words "$BD_VERIFY_WORDS" "$GOLDEN_BD_ARG" --out-dir "$DATA_DIR"

[[ -f "$EXPORT_VCS_DIR/lite.sh" ]] || {
  echo "ERROR: missing export scripts at $EXPORT_VCS_DIR — run 4_export_sim.tcl first" >&2
  exit 1
}

mkdir -p "$BUILD_DIR"

# BD IP sim wrappers (lite_dcim_ibuf_ctrl_0_0, lite_hbm_ref_clk_wiz_0, etc.) are generated
# by Vivado export_simulation into build/lite/lite.ip_user_files/bd/lite/ip/*/sim/.
# We use lite.sh to compile them; XILINX_VCS_LIB provides the base Xilinx IP precompiled library.
echo "=== Compile lite BD (Vivado export lite.sh) ==="
unset SYNOPSYS_SIM_SETUP
# Use axi_bram_ctrl vhdl.sdb as proxy: lite.sh compile completed iff this file is non-empty.
BRAM_CTRL_DB="$EXPORT_VCS_DIR/vcs_lib/axi_bram_ctrl_v4_1_12/64/vhdl.sdb"
if [[ "$SKIP_LITE_COMPILE" == "1" && -s "$BRAM_CTRL_DB" ]]; then
  echo "INFO: SKIP_LITE_COMPILE=1, reuse existing lite export compile (axi_bram_ctrl present)"
else
  (
    cd "$EXPORT_VCS_DIR"
    ./lite.sh -lib_map_path "$XILINX_VCS_LIB" -step compile 2>&1 | tee "$BUILD_DIR/export_compile.log"
  )
fi

# Refresh sim artifacts only; keep export compile results intact in EXPORT_VCS_DIR.
rm -rf "$BUILD_DIR/simv" "$BUILD_DIR/sim.log" "$BUILD_DIR/vlogan_rtl_extra.log" \
  "$BUILD_DIR/vlogan_tb.log" "$BUILD_DIR/vlogan_glbl.log" "$BUILD_DIR/compile.log" \
  "$BUILD_DIR/rtl_extra.f"
mkdir -p "$BUILD_DIR"
ln -sfn "$DATA_DIR"/*.hex "$BUILD_DIR/" 2>/dev/null || true

export SYNOPSYS_SIM_SETUP="$EXPORT_VCS_DIR/synopsys_sim.setup"

VCS_ELAB_OPTS=""
SIM_DUMP_PLUSARGS=""
ENABLE_FSDB_DEFINE=""
if [[ "$VCS_DUMP" == "1" ]]; then
  VCS_ELAB_OPTS="-kdb -lca -debug_access+all"
  SIM_DUMP_PLUSARGS="+DUMP_FSDB +FSDB=$DUMP_FSDB"
  ENABLE_FSDB_DEFINE="+define+ENABLE_FSDB"
fi

inc=(
  "+incdir+$REPO_ROOT/rtl/chip"
  "+incdir+$REPO_ROOT/rtl/vpu"
  "+incdir+$LITE_BD_DIR/data"
  "+incdir+$LITE_BD_DIR"
  "+incdir+$REPO_ROOT/build/lite/lite.ip_user_files/bd/lite/ip/lite_xdma_0_0/ip_0/source"
  "+incdir+$REPO_ROOT/bd/lite/ipshared/eebc/hdl/verilog"
  "+incdir+$REPO_ROOT/build/lite/lite.ip_user_files/bd/lite/ip/lite_hbm_0_0/hdl/rtl"
  "+incdir+$REPO_ROOT/bd/lite/ipshared/7b8c/verif/model"
  "+define+SIMULATION"
)
if [[ -n "$ENABLE_FSDB_DEFINE" ]]; then
  inc+=("$ENABLE_FSDB_DEFINE")
fi

echo "=== Vlogan user RTL into xil_defaultlib ==="
# Also compile the two VHDL wrappers for IBUF/OBUF AXI BRAM ctrl IPs.
# These are VHDL files generated by export_simulation that wrap axi_bram_ctrl_v4_1_12.
# Without this, lite_dcim_ibuf_ctrl_0_0 and lite_dcim_obuf_ctrl_0_0 are empty black-boxes.
(
  cd "$EXPORT_VCS_DIR"
  vhdlan -full64 -work xil_defaultlib \
    "$REPO_ROOT/build/lite/lite.ip_user_files/bd/lite/ip/lite_dcim_ibuf_ctrl_0_0/sim/lite_dcim_ibuf_ctrl_0_0.vhd" \
    "$REPO_ROOT/build/lite/lite.ip_user_files/bd/lite/ip/lite_dcim_obuf_ctrl_0_0/sim/lite_dcim_obuf_ctrl_0_0.vhd" \
    -l "$BUILD_DIR/vhdlan_bram_ctrl.log"
)
EXTRA_FL="$BUILD_DIR/rtl_extra.f"
bash "$BD_SIM_DIR/gen_bd_rtl_extra.sh" "$EXTRA_FL"
echo "=== BD/user RTL source audit ==="
echo "AUDIT: Vivado export BD/IP compile is under $EXPORT_VCS_DIR (lite.sh + synopsys_sim.setup)."
echo "AUDIT: Extra module_ref implementation RTL compiled from rtl_extra.f:"
sed 's#^#AUDIT:   #' "$EXTRA_FL"
echo "AUDIT: TB-only files compiled into work library:"
echo "AUDIT:   $LITE_BD_DIR/lite_xdma_constant_stub.v"
echo "AUDIT:   $LITE_BD_DIR/host_axi_master_bfm.sv"
echo "AUDIT:   $LITE_BD_DIR/tb_lite_bd_e2e.sv"
(
  cd "$EXPORT_VCS_DIR"
  "$VLOGAN" -full64 -sverilog +v2k "${inc[@]}" -work xil_defaultlib -f "$EXTRA_FL" \
    -l "$BUILD_DIR/vlogan_rtl_extra.log"
)

echo "=== Vlogan TB (work) ==="
(
  cd "$EXPORT_VCS_DIR"
  mkdir -p vcs_lib/work
  "$VLOGAN" -full64 -sverilog +v2k "${inc[@]}" -work work \
    "$LITE_BD_DIR/lite_xdma_constant_stub.v" \
    "$LITE_BD_DIR/host_axi_master_bfm.sv" \
    "$LITE_BD_DIR/tb_lite_bd_e2e.sv" \
    -l "$BUILD_DIR/vlogan_tb.log"
)

echo "=== VCS elaborate TB + lite ==="
(
  cd "$EXPORT_VCS_DIR"
  "$VCS" -full64 $VCS_ELAB_OPTS \
    -ignore initializer_driver_checks \
    +notimingcheck +nospecify \
    -t ps \
    work."$TB_TOP" xil_defaultlib.lite xil_defaultlib.glbl \
    -o "$BUILD_DIR/simv" -l "$BUILD_DIR/compile.log"
)

echo "=== VCS simulate lite BD ==="
(
  cd "$BUILD_DIR"
  "$BUILD_DIR/simv" +notimingcheck +nospecify +suppress=ASLR_DETECTED_INFO $SIM_PLUSARGS $SIM_DUMP_PLUSARGS 2>&1 | tee sim.log
)

grep -E "(AUDIT:|compare L|PASS,|FAIL ---|GRAND|ALL CHECKPOINTS|SOME CHECKPOINTS|FATAL|HOST_BFM|BD_E2E|DIAG\\[|PROGRESS: decoder)" "$BUILD_DIR/sim.log" | tail -80 || true

if grep -q 'SOME CHECKPOINTS FAILED\|FATAL' "$BUILD_DIR/sim.log"; then
  echo "ERROR: BD simulation FAILED (see $BUILD_DIR/sim.log)" >&2
  exit 1
fi
if grep -q 'ALL CHECKPOINTS PASSED' "$BUILD_DIR/sim.log"; then
  echo "BD VCS PASS (case=$BD_CASE mode=$BD_MODE)"
else
  echo "ERROR: BD sim did not report ALL CHECKPOINTS PASSED" >&2
  exit 1
fi
