# 生成 rtl/vpu/tb/mem_defines_auto.vh（绝对路径），供 $readmemh 使用。
set repoRoot [lindex $argv 0]
set outVh [file normalize [file join $repoRoot rtl/vpu/tb/mem_defines_auto.vh]]
set memDir [file normalize [file join $repoRoot rtl/vpu/tb/mem]]
set f [open $outVh w]
puts $f "// Auto-generated by gen_mem_defines.tcl — do not hand-edit."
puts $f "`ifndef MEM_DEFINES_AUTO_VH"
puts $f "`define MEM_DEFINES_AUTO_VH"
puts $f "`define MEM_MP_ACT \"$memDir/mp_act_data.mem\""
puts $f "`define MEM_MP_EXP \"$memDir/mp_expected_data.mem\""
puts $f "`define MEM_US_ACT \"$memDir/us_act_data.mem\""
puts $f "`define MEM_US_EXP \"$memDir/us_output_data.mem\""
puts $f "`endif"
close $f
puts "Wrote $outVh"
