#!/usr/bin/env python3
"""
golden_qa_standalone.py - QA unit standalone golden (YOLOv5n original params).

Uses scale=1.0 spatial dims and real act_scale / DQA outputs from the 3-layer
YOLO chain. Large tensors in hex files; SVH holds metadata + qscale only.

Usage:
  python3 tools/golden_qa_standalone.py
"""
from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import List, Sequence

import numpy as np

from net_standalone_common import (
    FP_CORE_NUM,
    build_yolo_layers,
    bytes_to_128_words,
    forward_all_layers,
    nhwc_flat_fp32,
    pack_fp32_obuf_words,
    qa_hw_qscale,
    write_hex,
)


@dataclass
class QaCase:
    name: str
    h: int
    w: int
    c: int
    qscale: float
    src_word_base: int
    dst_word_base: int
    n_in_words: int
    n_out_words: int
    expect_save_count: int
    in_hex: str
    out_hex: str
    poll_limit: int


def fp32_word_lines(values: Sequence[float]) -> List[str]:
    return [f"{w:032x}" for w in pack_fp32_obuf_words(values)]


def build_network_cases(scale: float, hex_dir: str) -> List[QaCase]:
    layers, _, _ = build_yolo_layers(scale)
    mids = forward_all_layers(layers)

    bases = [0x00000, 0x20000, 0x40000]
    cases = []

    for idx, (ly, mid) in enumerate(zip(layers, mids)):
        dqa = mid["dqa"]
        qa = ly.compute_qa(dqa)
        flat_fp = nhwc_flat_fp32(dqa.reshape(ly.oh, ly.ow, ly.out_ch))
        int8_blob = qa.reshape(-1).astype(np.int8).tobytes()
        out_lines = bytes_to_128_words(int8_blob)

        in_words = len(pack_fp32_obuf_words(flat_fp))
        out_words = len(out_lines)
        total_fp = ly.oh * ly.ow * ly.out_ch
        save_count = (total_fp + FP_CORE_NUM - 1) // FP_CORE_NUM

        src = bases[idx]
        dst = src + 0x10000

        in_hex = os.path.join(hex_dir, f"L{idx + 1}_qa_in.hex")
        out_hex = os.path.join(hex_dir, f"L{idx + 1}_qa_out.hex")
        write_hex(in_hex, fp32_word_lines(flat_fp))
        write_hex(out_hex, out_lines)

        poll = max(800_000, save_count * 80)

        cases.append(
            QaCase(
                name=f"L{idx + 1}_{ly.name}",
                h=ly.oh,
                w=ly.ow,
                c=ly.out_ch,
                qscale=qa_hw_qscale(ly.act_scale),
                src_word_base=src,
                dst_word_base=dst,
                n_in_words=in_words,
                n_out_words=out_words,
                expect_save_count=save_count,
                in_hex=os.path.basename(in_hex),
                out_hex=os.path.basename(out_hex),
                poll_limit=poll,
            )
        )
    return cases


def emit_svh(cases: Sequence[QaCase], path: str) -> None:
    import struct

    def fp32_to_bits(x: float) -> int:
        return struct.unpack(">I", struct.pack(">f", float(x)))[0]

    lines = [
        "// Auto-generated by tools/golden_qa_standalone.py — do not edit",
        f"// Network original params (default scale=1.0); E2E uses smaller scale for speed",
        "`ifndef QA_STANDALONE_GOLDEN_SVH",
        "`define QA_STANDALONE_GOLDEN_SVH",
        "",
        f"localparam int QA_STANDALONE_NUM_CASES = {len(cases)};",
        'localparam string QA_HEX_DIR = "hex/";',
        "",
    ]

    for idx, tc in enumerate(cases):
        qbits = fp32_to_bits(tc.qscale)
        lines.append(f"// Case {idx}: {tc.name}  {tc.h}x{tc.w}x{tc.c}")
        lines.append(f"localparam int QA_CASE_{idx}_H = {tc.h};")
        lines.append(f"localparam int QA_CASE_{idx}_W = {tc.w};")
        lines.append(f"localparam int QA_CASE_{idx}_C = {tc.c};")
        lines.append(f"localparam int QA_CASE_{idx}_SRC_BASE = {tc.src_word_base};")
        lines.append(f"localparam int QA_CASE_{idx}_DST_BASE = {tc.dst_word_base};")
        lines.append(f"localparam int QA_CASE_{idx}_N_IN_WORDS = {tc.n_in_words};")
        lines.append(f"localparam int QA_CASE_{idx}_N_OUT_WORDS = {tc.n_out_words};")
        lines.append(f"localparam int QA_CASE_{idx}_SAVE_COUNT = {tc.expect_save_count};")
        lines.append(f"localparam int QA_CASE_{idx}_POLL_LIMIT = {tc.poll_limit};")
        lines.append(f"localparam logic [31:0] QA_CASE_{idx}_QSCALE_BITS = 32'h{qbits:08x};")
        lines.append(f'localparam string QA_CASE_{idx}_IN_HEX  = {{QA_HEX_DIR, "{tc.in_hex}"}};')
        lines.append(f'localparam string QA_CASE_{idx}_OUT_HEX = {{QA_HEX_DIR, "{tc.out_hex}"}};')
        lines.append("")

    lines.append("`endif // QA_STANDALONE_GOLDEN_SVH")
    lines.append("")
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def self_check(cases: Sequence[QaCase], hex_dir: str) -> None:
    for tc in cases:
        assert os.path.isfile(os.path.join(hex_dir, tc.in_hex)), tc.in_hex
        assert os.path.isfile(os.path.join(hex_dir, tc.out_hex)), tc.out_hex


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scale", type=float, default=1.0)
    ap.add_argument(
        "--out-dir",
        default=os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "rtl",
            "vpu",
            "tb",
            "standalone",
            "generated",
        ),
    )
    args = ap.parse_args()
    out_dir = os.path.normpath(args.out_dir)
    hex_dir = os.path.join(out_dir, "hex")
    svh = os.path.join(out_dir, "qa_standalone_golden.svh")

    cases = build_network_cases(args.scale, hex_dir)
    self_check(cases, hex_dir)
    emit_svh(cases, svh)

    print(f"Wrote {len(cases)} QA network cases -> {svh}")
    print(f"  hex dir: {hex_dir}  (scale={args.scale})")
    for tc in cases:
        print(
            f"  {tc.name}: {tc.h}x{tc.w}x{tc.c} qscale={tc.qscale:.6g} "
            f"saves={tc.expect_save_count} out_words={tc.n_out_words}"
        )


if __name__ == "__main__":
    main()
