#!/usr/bin/env python3
"""
golden_dqa_standalone.py - DQA unit standalone golden (YOLOv5n original params).

Uses scale=1.0 spatial dims (L1 160x160 in → 80x80x32 out, etc.) and real
dqa_scale / dqa_bias from parsed weights. Large tensors go to hex files; SVH
holds metadata + small WB vectors only.

E2E may use --scale 0.1 in golden_e2e_inst.py for faster integration sim.

Usage:
  python3 tools/golden_dqa_standalone.py
  python3 tools/golden_dqa_standalone.py --scale 1.0 --out-dir rtl/vpu/tb/standalone/generated
"""
from __future__ import annotations

import argparse
import os
import struct
from dataclasses import dataclass
from typing import List, Sequence

import numpy as np

from net_standalone_common import (
    FP_CORE_NUM,
    accum_to_nhwc,
    build_yolo_layers,
    forward_all_layers,
    nhwc_flat_int32,
    pack_fp32_obuf_words,
    pack_int32_obuf_words,
    write_hex,
)


@dataclass
class DqaCase:
    name: str
    h: int
    w: int
    c: int
    scale: List[float]
    bias: List[float]
    scale_byte_addr: int
    bias_byte_addr: int
    src_word_base: int
    dst_word_base: int
    n_in_words: int
    n_out_words: int
    in_hex: str
    out_hex: str
    poll_limit: int


def fp32_word_lines(values: Sequence[float]) -> List[str]:
    return [f"{w:032x}" for w in pack_fp32_obuf_words(values)]


def int32_word_lines(values: Sequence[int]) -> List[str]:
    return [f"{w:032x}" for w in pack_int32_obuf_words(values)]


def build_network_cases(scale: float, hex_dir: str) -> List[DqaCase]:
    layers, _, _ = build_yolo_layers(scale)
    mids = forward_all_layers(layers)

    # Word bases spaced to fit largest layer (L1 ~51200 words)
    bases = [0x00000, 0x20000, 0x40000]
    cases = []

    for idx, (ly, mid) in enumerate(zip(layers, mids)):
        nhwc = accum_to_nhwc(mid["accum"], ly.oh, ly.ow, ly.out_ch)
        flat_i32 = nhwc_flat_int32(nhwc)
        dqa = mid["dqa"]
        flat_fp = dqa.reshape(-1).astype(np.float32).tolist()

        in_words = len(pack_int32_obuf_words(flat_i32))
        out_words = len(pack_fp32_obuf_words(flat_fp))
        src = bases[idx]
        dst = src + 0x10000

        in_hex = os.path.join(hex_dir, f"L{idx + 1}_dqa_in.hex")
        out_hex = os.path.join(hex_dir, f"L{idx + 1}_dqa_out.hex")
        write_hex(in_hex, int32_word_lines(flat_i32))
        write_hex(out_hex, fp32_word_lines(flat_fp))

        poll = max(500_000, out_words * 80)
        scale_byte_addr = 0
        # Align bias after scale region (same 256 B spacing as E2E wb_init layout).
        bias_byte_addr = (ly.out_ch * 4 + 255) & ~255

        cases.append(
            DqaCase(
                name=f"L{idx + 1}_{ly.name}",
                h=ly.oh,
                w=ly.ow,
                c=ly.out_ch,
                scale=ly.dqa_scale.astype(float).tolist(),
                bias=ly.dqa_bias.astype(float).tolist(),
                scale_byte_addr=scale_byte_addr,
                bias_byte_addr=bias_byte_addr,
                src_word_base=src,
                dst_word_base=dst,
                n_in_words=in_words,
                n_out_words=out_words,
                in_hex=os.path.basename(in_hex),
                out_hex=os.path.basename(out_hex),
                poll_limit=poll,
            )
        )
    return cases


def emit_svh(cases: Sequence[DqaCase], path: str) -> None:
    lines = [
        "// Auto-generated by tools/golden_dqa_standalone.py — do not edit",
        f"// Network original params (default scale=1.0); E2E uses smaller scale for speed",
        "`ifndef DQA_STANDALONE_GOLDEN_SVH",
        "`define DQA_STANDALONE_GOLDEN_SVH",
        "",
        f"localparam int DQA_STANDALONE_NUM_CASES = {len(cases)};",
        "localparam string DQA_HEX_DIR = \"hex/\";",
        "",
    ]

    for idx, tc in enumerate(cases):
        n_scale = (tc.c + 3) // 4
        n_bias = n_scale
        lines.append(f"// Case {idx}: {tc.name}  {tc.h}x{tc.w}x{tc.c}")
        lines.append(f"localparam int DQA_CASE_{idx}_H = {tc.h};")
        lines.append(f"localparam int DQA_CASE_{idx}_W = {tc.w};")
        lines.append(f"localparam int DQA_CASE_{idx}_C = {tc.c};")
        lines.append(f"localparam int DQA_CASE_{idx}_SRC_BASE = {tc.src_word_base};")
        lines.append(f"localparam int DQA_CASE_{idx}_DST_BASE = {tc.dst_word_base};")
        lines.append(f"localparam int DQA_CASE_{idx}_SCALE_BYTE_ADDR = {tc.scale_byte_addr};")
        lines.append(f"localparam int DQA_CASE_{idx}_BIAS_BYTE_ADDR = {tc.bias_byte_addr};")
        lines.append(f"localparam int DQA_CASE_{idx}_N_IN_WORDS = {tc.n_in_words};")
        lines.append(f"localparam int DQA_CASE_{idx}_N_OUT_WORDS = {tc.n_out_words};")
        lines.append(f"localparam int DQA_CASE_{idx}_POLL_LIMIT = {tc.poll_limit};")
        lines.append(f'localparam string DQA_CASE_{idx}_IN_HEX  = {{DQA_HEX_DIR, "{tc.in_hex}"}};')
        lines.append(f'localparam string DQA_CASE_{idx}_OUT_HEX = {{DQA_HEX_DIR, "{tc.out_hex}"}};')

        lines.append(f"localparam logic [127:0] DQA_CASE_{idx}_SCALE [{n_scale}] = '{{")
        for wi, w in enumerate(pack_fp32_obuf_words(tc.scale)):
            comma = "," if wi + 1 < n_scale else ""
            lines.append(f"    128'h{w:032x}{comma}")
        lines.append("};")

        lines.append(f"localparam logic [127:0] DQA_CASE_{idx}_BIAS [{n_bias}] = '{{")
        for wi, w in enumerate(pack_fp32_obuf_words(tc.bias)):
            comma = "," if wi + 1 < n_bias else ""
            lines.append(f"    128'h{w:032x}{comma}")
        lines.append("};")
        lines.append("")

    lines.append("`endif // DQA_STANDALONE_GOLDEN_SVH")
    lines.append("")
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def self_check(cases: Sequence[DqaCase], hex_dir: str) -> None:
    for tc in cases:
        in_path = os.path.join(hex_dir, tc.in_hex)
        assert os.path.isfile(in_path), in_path
        out_path = os.path.join(hex_dir, tc.out_hex)
        assert os.path.isfile(out_path), out_path
        assert tc.n_out_words == sum(1 for _ in open(out_path)), tc.name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="Spatial scale (default 1.0 = full 160x160 L1; E2E uses ~0.1)",
    )
    ap.add_argument(
        "--out-dir",
        default=os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "rtl",
            "vpu",
            "tb",
            "standalone",
            "generated",
        ),
    )
    args = ap.parse_args()
    out_dir = os.path.normpath(args.out_dir)
    hex_dir = os.path.join(out_dir, "hex")
    svh = os.path.join(out_dir, "dqa_standalone_golden.svh")

    cases = build_network_cases(args.scale, hex_dir)
    self_check(cases, hex_dir)
    emit_svh(cases, svh)

    print(f"Wrote {len(cases)} DQA network cases -> {svh}")
    print(f"  hex dir: {hex_dir}  (scale={args.scale})")
    for tc in cases:
        print(
            f"  {tc.name}: {tc.h}x{tc.w}x{tc.c} "
            f"in_words={tc.n_in_words} out_words={tc.n_out_words} poll={tc.poll_limit}"
        )


if __name__ == "__main__":
    main()
