###############################################################
#  Generated by:      Cadence Innovus 23.10-p003_1
#  OS:                Linux x86_64(Host ID t1centos7)
#  Generated on:      Tue Jul 15 13:12:34 2025
#  Design:            processor
#  Command:           create_ccopt_clock_tree_spec -file ../scripts/clock_tree/ccopt_cts_spec.tcl
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins were identified as implicit sinks
# The following pins are design outputs carrying SDC clocks
# These pins are ignore skew pins
set_ccopt_property sink_type -pin dco_clk_div ignore
set_ccopt_property sink_type_reasons -pin dco_clk_div {implicit design_io}

# The following pins are on the boundary of the STA clock network
# These pins are timing capture points
set_ccopt_property sink_type -pin cpu_inst/picorv32_core/RC_CG_HIER_INST48/RC_CGIC_INST/CP stop
set_ccopt_property sink_type_reasons -pin cpu_inst/picorv32_core/RC_CG_HIER_INST48/RC_CGIC_INST/CP no_sdc_clock

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin dco_inst/CLK true
set_ccopt_property cts_is_sdc_clock_root -pin dco_inst/CLK_DIV true

# Input pins determined constant across all timing configs.
set_ccopt_property case_analysis -pin bridge_inst/RC_CG_HIER_INST0/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin bridge_inst/RC_CG_HIER_INST1/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin bridge_inst/RC_CG_HIER_INST2/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/axi_adapter/RC_CG_HIER_INST61/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_DECLONE_HIER_INST/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST10/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST11/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST12/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST13/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST14/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST15/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST16/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST17/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST18/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST19/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST20/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST21/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST22/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST23/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST24/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST25/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST26/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST27/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST28/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST29/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST3/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST30/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST31/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST32/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST33/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST34/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST35/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST36/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST37/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST38/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST39/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST4/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST40/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST41/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST42/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST43/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST44/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST45/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST46/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST47/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST49/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST5/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST51/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST52/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST53/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST55/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST6/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST60/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST7/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST8/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/RC_CG_HIER_INST9/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/genblk1.pcpi_mul/RC_CG_HIER_INST58/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/genblk1.pcpi_mul/RC_CG_HIER_INST59/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/genblk2.pcpi_div/RC_CG_HIER_INST56/RC_CGIC_INST/TE 0
set_ccopt_property case_analysis -pin cpu_inst/picorv32_core/genblk2.pcpi_div/RC_CG_HIER_INST57/RC_CGIC_INST/TE 0

# Clocks present at pin dco_inst/CLK_DIV
#   clk_div (period 64.000ns) in timing_config func([/DISK1/home/rh_xu30/work/share/innovus_template/pnr/processor/backup/processor_postPlace.enc.dat/mmmc/modes/func/func.sdc])
#   clk (period 2.000ns) in timing_config func([/DISK1/home/rh_xu30/work/share/innovus_template/pnr/processor/backup/processor_postPlace.enc.dat/mmmc/modes/func/func.sdc]) (generator)
create_ccopt_clock_tree -name clk_div -source dco_inst/CLK_DIV -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner tt_0p80v_25c -early -clock_tree clk_div 0.100
set_ccopt_property target_max_trans_sdc -delay_corner tt_0p80v_25c -late -clock_tree clk_div 0.100
# Clock period setting for source pin of clk_div
set_ccopt_property clock_period -pin dco_inst/CLK_DIV 2

# Clocks present at pin dco_inst/CLK
#   clk (period 2.000ns) in timing_config func([/DISK1/home/rh_xu30/work/share/innovus_template/pnr/processor/backup/processor_postPlace.enc.dat/mmmc/modes/func/func.sdc])
create_ccopt_clock_tree -name clk -source dco_inst/CLK -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner tt_0p80v_25c -early -clock_tree clk 0.100
set_ccopt_property target_max_trans_sdc -delay_corner tt_0p80v_25c -late -clock_tree clk 0.100
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin dco_inst/CLK 2

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:func (sdc /DISK1/home/rh_xu30/work/share/innovus_template/pnr/processor/backup/processor_postPlace.enc.dat/mmmc/modes/func/func.sdc)
create_ccopt_skew_group -name clk/func -sources dco_inst/CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/func true
set_ccopt_property extracted_from_clock_name -skew_group clk/func clk
set_ccopt_property extracted_from_constraint_mode_names -skew_group clk/func {func  }
set_ccopt_property extracted_from_delay_corners -skew_group clk/func tt_0p80v_25c

# This is a constraining skew group to balance generated clock:clk_div in timing_config:func (sdc /DISK1/home/rh_xu30/work/share/innovus_template/pnr/processor/backup/processor_postPlace.enc.dat/mmmc/modes/func/func.sdc)
# because no path could be found to the master clock.
#   immediate master: clock:clk in timing_config func
#    ultimate master: clock:clk in timing_config func
create_ccopt_skew_group -name clk_div/func -sources dco_inst/CLK_DIV -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_div/func true
set_ccopt_property extracted_from_clock_name -skew_group clk_div/func clk_div
set_ccopt_property extracted_from_constraint_mode_names -skew_group clk_div/func {func  }
set_ccopt_property extracted_from_delay_corners -skew_group clk_div/func tt_0p80v_25c


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

